import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { System } from '../_components';
import './global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Unsplash Next.js Clone App',
  description: 'Generated by create next app',
};

type RootLayoutProps = Readonly<{
  children: React.ReactNode;
}>;

const RootLayout: React.FC<RootLayoutProps> = (props) => {
  const { children } = props;

  return (
    <html lang="ko">
      <body className={inter.className}>
        <System>{children}</System>
      </body>
    </html>
  );
};

export default RootLayout;
